### ISSUE TITLE
Function keys in examples do not work

### ISSUE THREAD

**Issue by Culminate** [daniele77/cli#58] opened 2020-02-28 14:37 UTC
Hi.
Keys tab, up, down, left, right, backspace, home, end do not work in examples (asyncsession.cpp, simplesession.cpp).
I delete telnet session from complete.cpp, but the program ended immediately.

**Comment by daniele77** [comment] 2020-02-28 15:45
Yes, it's by design: special keys work only with `CliLocalTerminalSession`, but not with `CliFileSession `or `CliAsyncSession`.

As for as the telnet session removed from `complete.cpp`: it's ok, it's how `boost::asio::io_context` works. You must assign some dummy work to it to keep it running. You can do that with the following code:

    #if BOOST_VERSION < 106600
        boost::asio::io_service::work work(ios);
    #else
        auto work = boost::asio::make_work_guard(ios);
    #endif

resulting in:

        ...
        CliLocalTerminalSession localSession(cli, ios, std::cout, 200);
        localSession.ExitAction(
            [&ios](auto& out) // session exit action
            {
                out << "Closing App...\n";
                ios.stop();
            }
        );

    #if BOOST_VERSION < 106600
        boost::asio::io_service::work work(ios);
    #else
        auto work = boost::asio::make_work_guard(ios);
    #endif
        ios.run();
        return 0;
    }

**Closed by daniele77** 2020-02-28 15:45 UTC
